<?php
	//开始生成配置文件
	function getRandStr($length) 
		{  
			$str = 'abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%%^&*()';
			$randString = '';
			$len = strlen($str)-1;
			for($i = 0;$i < $length;$i ++){ 
				$num = mt_rand(0, $len);
				$randString .= $str[$num];
				} 
			return $randString ;
		}
	
    function autoconfig()
    {
       exec("echo $OPENSHIFT_MYSQL_DB_HOST",$DBHOST);
	   exec("echo $OPENSHIFT_MYSQL_DB_USERNAME",$DBUSER);
	   exec("echo $OPENSHIFT_MYSQL_DB_PASSWORD",$DBPW);
	   exec("echo $OPENSHIFT_GEAR_NAME",$DBNAME);
	   $SALT = getRandStr($length=20);
	   $configfile = fopen("../config.php","w");
	   $text = "<?php if (!defined('SYSTEM_ROOT')) { die('Insufficient Permissions'); }\n";
	   $text = $text . "define('DB_HOST','"+$DBHOST+"');\n";
	   $text = $text . "define('DB_USER','"+$DBUSER+"');\n";
	   $text = $text . "define('DB_PASSWD','"+$DBPW+"');\n";
	   $text = $text . "define('DB_PASSWD','"+$DBNAME+"');\n";
	   $text = $text . "define('DB_PREFIX','tc_');\n";
	   $text = $text . "define('SYSTEM_SALT','"+$SALT+"');\n";
	   $text = $text . "//This config file was generated by the Tieba-Cloud-Sign-OpenShift-QuickStart. Please edit after you know why and how to edit this file.\n";
	   $text = $text . "//本文件由Tieba-Cloud-Sign-OpenShift-QuickStart生成，请在明白为什么/怎么编辑之后进行编辑";
	   fwrite($configfile,$text);
    }
	//开始安装
    //$USERNAME = $_POST["name"];
    //$USERMAIL = $_POST["mail"];
    //$USERPW = $_POST["pw"];
	//define('DB_HOST',$DBHOST);
	//define('DB_USER',$DBUSER);
	//define('DB_PASSWD',$DBPW);
	//define('DB_NAME',$DBNAME);
	//define('DB_PREFIX','tc_');
	//define('SYSTEM_SALT',$SALT);
    //define('ISAPP',0);
	//if (isset($_SERVER['HTTPS']) == 'on') {
	//				$http = 'https://';
	//			} else {
	//				$http = 'http://';
	//			}
    //
    //$sql_dbtemplate = fopen("install.template.sql","r");
    //$sql_command = fread($sql_dbtemplate,filesize("install.template.sql"));
    //fclose($sql_dbtemplate);
    //$sql_command = str_replace("{VAR-PREFIX}",DB_PREFIX,$sql_command);
    //$sql_command = str_replace("{VAR-DB}",DB_NAME,$sql_command);
    //$sql_command = str_replace("{VAR-ISAPP}",ISAPP,$sql_command);
    //$sql_command = str_replace("{VAR-TOOLPW}",'',$sql_command);
    //$sql_command = str_replace("{VAR-SYSTEM-URL}",$http . $_SERVER['HTTP_HOST'] . str_replace('setup/','',$sysurl[0]),$sql_command);
    //$sql_command .=  "\n"."INSERT INTO `".DB_NAME."`.`".DB_PREFIX."users` (`name`, `pw`, `email`, `role`) VALUES ('" .$USERNAME. "', '".md5(md5(md5($USERPW)))."', '"$USERMAIL"', 'admin');";
    //$mysqlconnection = mysql_connect(DB_HOST,DB_USER,DB_PASSWD);
    //if (!$mysqlconnection)
    //    {
    //        die('Could not connect: ' . mysql_error());
    //    }
    //mysql_select_db(DB_NAME,$mysqlconnection);
    //mysql_query($sql_command,$mysqlconnection);
    //mysql_close($mysqlconnection);
    //
    //生成Cron脚本
    //$cron_sh = fopen("do.sh","w");
    //$cron_command = "php".dirname(__FILE__)."do.php"
    //fwrite($cron_sh,$cron_command);
    //exec("./cron.sh");
    
    //返回成功信息和提示
?>